### ISSUE TITLE
Probleme auf der Oberthal mit Weiß/Rotkohl und Zwiebeln

### ISSUE THREAD

**Issue by timmi4026** [tn4799/DynamicMissionVehicles#10]
Hallo, habe auf der Oberthal Probleme beim ernten von Rot/Weißkohl und den Zwiebeln. Alles andere geht, auch die neuen DLC Früchte.
Die Oberthal hat einen ähnlichen Script wie euren, aber den hab ich deaktiviert.  Habt Ihr da vielleicht eine Idee?

**Comment by tn4799** [comment]
Kannst du mir bitte einen Link zu der Map schicken?

Und beschreib mal bitte genau, was die Probleme sind, die du mit den Früchten hast.
Optimalerweise bitte auch mal noch die Log anhängen.

**Comment by tn4799** [comment]
Ich hab gestern mal n bissl mit FalPos geredet. Der Grund, weshalb die Erdfrüchte mit meinem Pack nicht funktionieren, ist, dass man bei denen kein Kraut entfernen muss.

**Comment by timmi4026** [comment]
Ok danke für die Info.

**Comment by tn4799** [comment]
Aktivier das Skript mal wieder, dann sollte es funktionieren. 
Alternativ füg eine fruitTypeCategory namens "EARTHFRUITS" zur map hinzu, die die erdfrüchte enthält. Dann sollten die Ernter funktionieren.

**Comment by timmi4026** [comment]
ok mach ich an, dachte nur das es sich beißen könnte, und die Kategorie ist in der Map schon vorhanden.
