### ISSUE TITLE
Incompatible trailers for potatoes, sugar beets and other related crops

### ISSUE THREAD

**Issue by KZumbusch** [tn4799/DynamicMissionVehicles#13]
I've added Dynamic Mission Vehicles to my existing savegame where I also use the Better Contracts mod. With both mods enabled I get offered harvesting contracts with incompatible trailers. Harvesting contracts for potatoes, sugar beet, red beet, carrots or parsnip are offered with the American style Wilson and Lode King trailers which do not support those crops. The provided harvesters are working as expected and I even get the harvesters from the Mutli Fruit Harvester Pack for the contracts.

As soon as I remove Dynamic Mission Vehicles from my savegame, clear and regenerate the contracts via Better Contracts, the Wilson and Lode King trailers are no longer offered with contracts.

I have a bunch of mods installed but Better Contracts and Dynamic Mission Vehicles are the only mods related to contracts.

Map: Hobo's Hollow 4x - 1.3.0.0
Better Contracts - 1.2.8.7
Dynamic Mission Vehicles - 1.2.0.1
Full mods list: see attached text file
[modlist.txt](https://github.com/tn4799/DynamicMissionVehicles/files/14231035/modlist.txt)

I can provide the full savegame or logfiles if required.

**Comment by tn4799** [comment]
Thanks for the report of the problem.
I've took giants mission vehicles for potato and sugar beet harvesting, and changed it. But it seems like, that they added incompatible trailers, which resulted in the same issue with my backup xml.
I wll fix it within the next update.
