### ISSUE TITLE
Potato harvesting

### ISSUE THREAD

**Issue by WeAreV3N0M** [tn4799/DynamicMissionVehicles#2]
The mod generates potato harvesting missions with incorrect machinery. 
Such as:
- cotton harvester with cotton trailer
- bottom dump hopper trailer (which can't hold potato). 

Please take a look at the code and fix these bugs.

**Comment by tn4799** [comment]
If you have incorrect mission vehicles then delete your missions.xml in the savegame file. 
Patch 1.8.1 did mess things up when it comes to mission vehicles for existing missions. 

If the problem still occurs after doing that then please send some screenshots of the mission and attach the log.txt
