### ISSUE TITLE
[BUG] Cant harvest seperate fruits without reseting

### ISSUE THREAD

**Issue by tn4799** [tn4799/DynamicMissionVehicles#20]
Moin, was mir heute aufgefallen ist, ist folgendes.

Hab erst Rote Beete geerntet und wollte danach Kartoffeln ernten. Leider funktionierte das nicht. Erst als ich den Roder und Schneidwerk zurückgesetzt hatte funktioniert es erst. Ich denke das ist nicht der Sinn dahinter.

Ich muss aber dazu sagen das die Umsetzung mit dem Script total Hammer ist. Danke dafür.

_Originally posted by @RumsdeBums in https://github.com/tn4799/DynamicMissionVehicles/issues/16#issuecomment-2227421024_

**Comment by tn4799** [comment]
@RumsdeBums Das ist komisch. Weil das war n Bug, der kurz nachm Release vom Platinum Pack aufgetreten ist, den ich jedoch schnell gefixt hab. Bist du denn auf der aktuellen Version?

**Comment by RumsdeBums** [comment]
Moin. Das Multi Fruit Harvester Pack ist bei mir die Version 1.1.0.0.

Dort ist der Changelog für die Premium Erweiterung hinterlegt.

**Comment by tn4799** [comment]
Dann solltest du mal updaten. die 1.1.0.1 ist schon seit ewigkeiten draußen

**Comment by RumsdeBums** [comment]
> Dann solltest du mal updaten. die 1.1.0.1 ist schon seit ewigkeiten draußen

Danke. Hab ich gar nicht mitbekommen.
