### ISSUE TITLE
Harvester Pack Multifruit

### ISSUE THREAD

**Issue by FWSWBN** [tn4799/DynamicMissionVehicles#3]
Servus Tim,

habe extra dafür einen Account erstellt, hoffe das alles passt und ich im richtigen Bereich bin.

Es geht um folgendes:

Ich habe die Map NF Marsch 4x OG in Version 2.3

Dort sind neben Weiskohl (whiteCabbage) auch Rotkohl (redCabbage) verbaut.
Leider erkennt dein Mod diese beiden Feldfrüchte nicht automatisch und manuell zufügen habe ich keine Möglichkeit gefunden weil bei Dir "Earthfruits" drinnen steht anstatt der verschiedenen Fruchtarten.

Wäre es Dir möglich .....

1. deinen Mod zu bearbeiten dass er auch Rot- und Weiskohl kennt
oder
2. mir eine Info zu geben wie ich das selbst ändern kann.

Was auch noch toll wäre und was mich persönlich sehr freuen würde wenn es eine Farbwahl geben würde, damit man sich die Fahrzeuge individuell anpassen kann (muss nicht unbedingt sein, wäre aber echt Klasse).

Kannst Dich auch gerne im Giants Forum bei mir melden (gleicher Name wie hier "FWSWBN")

Viele Grüße
Frank aka FWSWBN

**Comment by tn4799** [comment]
Hallo FWSWBN,
sorry, hab vergessen, dass es das Issue noch gibt.
Kannst du mir bitte mal die fruitTypes.xml von der map schicken? Sollten rot- und weißkohl kein kraut entfernen haben werden diese nicht als erdfrucht erkannt und somit auch nicht in den erntern eingetragen.

**Comment by LamaiK** [comment]
Hallo tn4799
Danke für deine Arbeit an den Scripten, hast du nicht Lust diese auch für andere "fruitTypes" zur Verfügung zu stellen so wie es der TheDjCHI im LS19 gemacht hat?
Dann könnten wir wieder all unsere Multifrüchtekarten damit ausstatten?
Danke für deine Erwägung.
Grüsse LamaiK

**Comment by FWSWBN** [comment]
Servus,
 
lang ist es her ^^ .... 
aber hauptsache es kommt überhaupt ein lebenszeichen.
 
hoffe das das die richtige datei ist.
 
ist direkt aus der map (zip file)
 
gruss
frank  
 
 
am Dienstag, 24. Januar 2023 um 14:56 schrieben Sie:

**Comment by tn4799** [comment]
> Hallo tn4799 Danke für deine Arbeit an den Scripten, hast du nicht Lust diese auch für andere "fruitTypes" zur Verfügung zu stellen so wie es der TheDjCHI im LS19 gemacht hat? Dann könnten wir wieder all unsere Multifrüchtekarten damit ausstatten? Danke für deine Erwägung. Grüsse LamaiK

Hallo @LamaiK,
was meinst du? Dass ich Früchte zur Verfügung stellen soll, die die Mapper in die Karten einbauen können? Oder auf was willst du hinaus? Das wird mir bisher nicht wirklich klar. Weil das ganze Fruchterkennungs- und Multifruchtroderskript basiert auf dem Skript von TheDjCHI aus dem LS19.

**Comment by tn4799** [comment]
@FWSWBN Da du per Email geantwortet hast, habe ich die XML nicht bekommen. Bitte antworte über Github Desktop oder die Webseite und häng hier die Datei an. Danke.

**Comment by FWSWBN** [comment]
Alter Schwede.
jetzt willst die XML hochladen und bekommst die Info ... "We dont support that file type" ^^

hab mal die Endung von .XML zu .TXT geändert.
[maps_fruitTypes.txt](https://github.com/tn4799/DynamicMissionVehicles/files/10498045/maps_fruitTypes.txt)

hoffe das das jetzt geht.

**Comment by tn4799** [comment]
```xml
<harvest minHarvestingGrowthState="9" maxHarvestingGrowthState="9" cutState="8" allowsPartialGrowthState="false" literPerSqm="3.78"/>
```
Hab in der xml jetzt nur whiteCabbage gefunden, aber das prinzip wird wahrscheinlich das gleiche sein.
Das problem, dass die früchte nicht erkannt werden, ist dass der minHarvestGrowthState zu niedrig war. Wenn du die harvest-zeile von whiteCabbage durch diese zeile ersetzt sollten die früchte erkannt werden und somit auch in die roder eingetragen.

**Comment by FWSWBN** [comment]
Servus,
habs mal geändert.... geht ohne Probleme 👍 

2 kleine Wünsche hätte ich noch (wenn es machbar ist für Dich).

1. Farbwahl er Maschine und Anbauteile wie Ernter und Anhänger
2. mehr Arbeitsbreite (sagen wir 3 mal oder 4 mal so breit wie es jetzt ist) <--- ich weis unrealistisch, aber bei Feldern mit 100 und mehr Hektar finde ich stört mich das nicht, ich ändere ja auch die capacity von den Fahrzeugen damit die nicht gleich nach 10 Metern voll sind.

Wäre Klasse wenn Du das machen könntest oder mir nen Tipp geben kannst wie ich das selbst ändern kann.

**Comment by LamaiK** [comment]
Hallo tn4799
Nein nicht die Früchte diese haben wir, nur so wie es bei TheDjCHI war das wir die Früchte in den XML`s eintragen können so dass die Ernter und die Schneidwerke mit den Früchten der jeweiligen Map zu ernten sind.
Bsp.:  Aus LS19 das Grimme FT300 Schneidwerk
```
    <fruitPreparer fruitType="sugarBeet lettuce redCabbage cabbage">
    </fruitPreparer>
```
Oder: Aus LS19 der Grimme rootster604 Ernter
```
    <fillUnit>
        <fillUnitConfigurations>
            <fillUnitConfiguration>
                <fillUnits>
                    <fillUnit unit="$l10n_unit_literShort" fillTypes="sugarBeet lettuce redCabbage cabbage" capacity="6000"/>
                </fillUnits>
            </fillUnitConfiguration>
        </fillUnitConfigurations>
    </fillUnit>
```
Das ist auch das was @FWSWBN meinte mit XML-Anpassungen, können wir dann nach Bedarf anpassen.

**Comment by tn4799** [comment]
@FWSWBN Farbwahl kann ich mal kucken, Arbeitsbreite wird nichts, da wird Giants garantiert nicht mitspielen.
Aber die arbeitsbreite kannst du manuell anpassen indem du in der i3d die TGs der workArea weiter voneinander weg schiebst.
https://forum.giants-software.com/viewtopic.php?t=184672
Hier solltest auch noch was finden wo dir diesbezüglich helfen sollte.

@LamaiK du kannst auch fruitTypes zusätzlich zur fruitTypeCategory noch eintragen. mittels `fruitTypes="..."` hab ich nur in den erntern nicht reingeschrieben weil ichs net brauche, da alle fruchtarten, die meine Roder von selbst können sollen, vom skript automatisch in die fruitTypeCategory eingetragen werden.

**Comment by LamaiK** [comment]
Dankeschön, bin grad auf dem Schlauch gestanden, mehr als dein Skript braucht es gar nicht, alles läuft wie es soll.

Grüsse LamaiK

**Comment by ScTeufel** [comment]
Hallöchen und gute Arbeit mit deinem Mod!

Frage: Kann es sein das in deinem Backup Datei der Markierte eintrag Falsch ist?
Da dieser Trailer gar keine Kartoffeln (Potato) Laden kan.

LG der Teufel

![LS 22 Mod](https://user-images.githubusercontent.com/123567007/214592046-0edd8532-849e-4600-a870-f84232441f12.JPG)
