### ISSUE TITLE
Harvester hält bei 100 % nicht an (Courseplay)

### ISSUE THREAD

**Issue by WestClown** [tn4799/DynamicMissionVehicles#5]
Hallöchen,

ich nutze den Harvester auf der Italia Emilia Ext SP. Für die Arbeiten nutze ich AD und CP. Jetzt ist mir bei der ersten Kartoffelernte aufgefallen, dass der Harvester nicht anhält, wenn der Bunker voll ist und er normalerweise warten würde, bis er überladen konnte.

Gibt es dafür einen speziellen Grund oder handelt es sich dabei um einen Fehler?

Beste Grüße

Markus

**Comment by tn4799** [comment]
Hm. Da bleiben gleich mal mehrere Fragen offen:

1. Welchen Ernter meinst du? Es gibt schließlich mehrere im Pack.
2. Wo ist die log.txt?
3. Kannst du bitte Screenshots anhängen

**Comment by WestClown** [comment]
Zu 1.:
Beide Maschinen, jeweils mit beiden Vorsätzen.
![Unbenannt](https://github.com/tn4799/DynamicMissionVehicles/assets/143606335/c17bec3a-d523-439d-ae3c-8ca29e7e04ec)

Zu 2.:
[log.txt](https://github.com/tn4799/DynamicMissionVehicles/files/12478998/log.txt)


Zu 3.:
Als Screenshot lässt es sich nicht wirklich besser darstellen.
Wie man sieht, ist der Bunker voll. Normalerweise würde der Ernter jetzt anhalten, bis ein Abfahrer zum Abbunkern kommt. In diesem Fall allerdings, werden keine Kartoffeln mehr geerntet, aber weiter Kraut geschlagen. Lasse ich den Fahrer im Anschluss nochmal fahren, dann fährt er auch wieder weiter, ohne dabei zu ernten oder Kraut zu schlagen.
![Unbenannt1](https://github.com/tn4799/DynamicMissionVehicles/assets/143606335/9b427b9f-3836-4c3b-a53f-e596b91e219d)

**Comment by tn4799** [comment]
Ah, das problem kenn ich von CP.
Da cp nach dem füllstand geht, das gewichtslimit aber ignoriert, wird der Fahrer von CP nicht gestoppt weil ja noch platz im bunker ist. 

Das Gewicht der Ernter ist auf das gesetzt, was GIANTS bei den Erntern ursprünglich eingestellt hat. Andere Erdfrüchte haben natürlich ein anderes Gewicht, wodurch dieses Phänomen auftreten kann. 

Der einfachste Workaround wäre das Deaktivieren des Gewichtlimits.

**Comment by tn4799** [comment]
Bzw. teste mal wie sich der GIANTS standard helfer verhält. 
Stoppt der oder arbeitet dieser auch weiter?

**Comment by WestClown** [comment]
Bei deaktiviertem Fülllimit funktioniert es sowohl beim Standard- als auch beim CP-Helfer ohne Probleme. Es liegt tatsächlich an der "fehlenden Füllung"; in diesem Fall 361 Liter.

Danke für deine Hilfe!

**Comment by tn4799** [comment]
Gerne. 

Hab bei CP auch schon mal n kleinen Patch geschrieben für das Weight-Problem. Muss ihn nur mal noch testen, wenns funzt mach ich ne PR bei CP auf mit dem Fix.

Würd mich nur mal interessieren, wie sich GIANTS ihr Helfer verhält, wenn man das Gewichtslimit aktiv hat und dann der tank voll wird.
