### ISSUE TITLE
missionVehicles.xml path names syntax inconsistent to vanilla behaviour

### ISSUE THREAD

**Issue by Gordon-Dry** [tn4799/DynamicMissionVehicles#6]
The path syntax is incompatible to vanilla entries.

### Examples

A map ships the missionVehicles.xml with a syntax like this for vehicles which are inside the map folder structure:
`<vehicle filename="maps/vehicles/rexor6300_onion.xml" />`
which works when FS22_DynamicMissionVehicles is not used.
But it has to be changed to 
`<vehicle filename="FS22_NF_Marsch_4fach/maps/vehicles/rexor6300_onion.xml" />`
to make it work with FS22_DynamicMissionVehicles.

Also the Precision Farming DLC ships a missionVehicles.xml which contains
`<vehicle filename="johnDeere/r700i/r700i.xml">`
which works when FS22_DynamicMissionVehicles is not used and needs to be changed to
`<vehicle filename="FS22_precisionFarming/vehicles/johnDeere/r700i/r700i.xml">`
to make it work with FS22_DynamicMissionVehicles.

**Comment by Gordon-Dry** [comment]
^updated because I forgot the Markdown formatting.

**Comment by tn4799** [comment]
Thanks for the feedback.
The inconsistency is currently needed because of the posibility to use vehicles of the mod folder as mission vehicles. 
But i have an idea in mind how i can improve this and make the mission vehicles syntax consistent between base game and my mod.

**Comment by Gordon-Dry** [comment]
Testing repo, just downloaded.
I did not see that there were already some commits two weeks ago.

**Comment by Gordon-Dry** [comment]
Hmm, now I get a log spam of this:
```
2023-12-07 18:47 Error: Running LUA method 'update'.
scripts/missions/MissionManagerExtension.lua(180) : bad argument #1 to 'ipairs' (table expected, got nil)
```
with the need of force killing the process.

**Comment by tn4799** [comment]
Thanks for trying, but im still in development. I will submit an update to the modhub (and add a release here on github) with the working Version.

**Comment by tn4799** [comment]
> Hmm, now I get a log spam of this:
> 
> ```
> 2023-12-07 18:47 Error: Running LUA method 'update'.
> scripts/missions/MissionManagerExtension.lua(180) : bad argument #1 to 'ipairs' (table expected, got nil)
> ```
> 
> with the need of force killing the process.

Which DLCs and mods did you use when this error occured. because in my mod there is no such file as a MissionManagerExtension

**Comment by Gordon-Dry** [comment]
A lot - this is my latest session's log without that mod:
[log.zip](https://github.com/tn4799/DynamicMissionVehicles/files/13696527/log.zip)
