### ISSUE TITLE
Harvester Pack Multifruit & Premium DLC

### ISSUE THREAD

**Issue by 37cee** [tn4799/DynamicMissionVehicles#9]
Hallo,
Ich habe mich gewundert, ob es möglich ist, den "Multi Fruit Harvester Pack" Fahrzeugen auch die neuen Fruchtsorten aus den Premium DLC beizubringen?

Also in der Theorie weiss ich, dass es funktioniert, da es ja schon ein paar Fahrzeuge gibt. Allerdings sind es immer komplette Fahrzeuge, die aus dem Basisspiel exportiert wurden [habe ich schon selbst versucht, aber bei mir scheitert es dann an den Texturen]. 

Eine Lösung wie dein "Multi Fruit Harvester Pack" fände ich persönlich bedeutend eleganter.

Falls das hier das falsche github repository, bitte ich um Entschuldigung, ich habe zum Harvester pack kein eigenständiges gefunden (und die Giant Webseite verweist hierher).

schönen Tag noch und danke für die Arbeit die Ihr (Modder)  in das Spiel investiert.

**Comment by tn4799** [comment]
Hi.
Steht defintiv aufm Plan, das skript so anzupassen, dass die neuen Erdfrüchte auch erkannt werden. 
Kann aber noch nicht sagen, wie lang es dauern wird.

Und vielen dank für die netten Worte.

Grüße
tn4799

**Comment by XSunFireX** [comment]
Hey,
schön wäre es dazu, wenn man die Farben selber gestalten könnte, was ein weitere Pluspunt mit sich bringen würde, hoffe das lässt sich auch umsetzen :)

**Comment by tn4799** [comment]
> Hey,
> schön wäre es dazu, wenn man die Farben selber gestalten könnte, was ein weitere Pluspunt mit sich bringen würde, hoffe das lässt sich auch umsetzen :) 

Was genau wünschst du dir denn?
Es gibt den mod ColorConfigurator. Mit dem kannst du nämlich Farben so anpassen wie du es haben willst.
